# CONFIGURATION FILE FOR CLIENT

mode: "classification" # choices: classification, detection

# MODEL
model_folder: CLIENT_MODEL
model_name: client.pth
arch: "resnet18"

# IP
HOST: "127.0.0.1"
PORT: 9865

#CLIENT PORT
CLIENT_PORT: 52475
# DATASET
labels:
  [
    "epidural",
    "intraparenchymal",
    "intraventricular",
    "subarachnoid",
    "subdural",
    "any",
  ]
n_classes: 6 # should match len(labels)

# TRANSFORMS
# TODO

# TRAINING
train_csv_file: ""
train_image_dir: ""
train_batch_size: 64

# PARAMS
epochs: 15
lr: 0.00002
device: "cuda" # choices: cpu, cuda
optimizer: "Adam" # choices: Adam, SGD

# TESTING
test_csv_file: ""
test_image_dir: ""
test: False # need to see logic, idea is to use when only training and not validating
test_batch_size: 1
